spring:
  profiles:
    active: test
---
server:
  port: 9010
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka8091.com:8091/eureka
---
server:
  port: 9011
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka8091.com:8091/eureka
