spring:
  profiles:
    active:
    - test
---
server:
  port: 9010
spring:
  profiles: dev     #开发环境
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka8091.com:8091/eureka
  instance:
    instance-id: product-service
    prefer-ip-address: true
---
server: 
  port: 9011
spring:
  profiles: test   #测试环境
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka8091.com:8091/eureka
  instance:
    instance-id: product-service
    prefer-ip-address: true
#  请保存为UTF-8格式
 
